# api urls
LOCAL_URL = 'http://localhost:5000'
API_LOGIN = '/login/submit'
API_REGISTER = '/registration'
API_WATCHLIST_ADD = "/watch/add"
API_WATCHLIST_REMOVE = "/watch/remove"
API_REFRESH = "/token/refresh"
API_LOGOUT = "/logout/access"
API_LOGOUT_REFRESH = "/logout/refresh"
API_STOCK_PURCHASE_SELL = "/stock/purchase"
API_STOCK = "/stock"
ACCESS_COOKIE = 'user_access'
REFRESH_COOKIE = 'user_refresh'
